### ISSUE TITLE
Set Priority as a Tag instead of Documentation

### ISSUE THREAD

**Issue by doamaral** [KatarinaMariano-QA/QA_Academy_Challenge_Robot_Framework#1]
Currently you're using `[Documentation]` to set test priority. Why don't you set priority as a test tag, instead?

Here a description https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tagging-test-cases

**Comment by KatarinaMariano-QA** [comment]
Improvement implemented.

**Comment by doamaral** [comment]
Well Done!
