### ISSUE TITLE
Extensive use of XPATH on POM files

### ISSUE THREAD

**Issue by doamaral** [KatarinaMariano-QA/QA_Academy_Challenge_Robot_Framework#2]
Page Objects files are extensively using XPATH for Interaction with Links. Maybe you could use the link text or href once `Click Link` keyword supports it

`menu_page.robot`
```
*** Variables ***
${ACCOUNT_MENU}            xpath=//a[contains(.,'Contas')]
${OPTION_ADD_ACCOUNT}      xpath=//a[contains(.,'Adicionar')]
${OPTION_ACCOUNT_LIST}     xpath=//a[contains(.,'Listar')]
```
find this out at Robot doc:
https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Click%20Link

**Comment by KatarinaMariano-QA** [comment]
Improvement implemented.

**Comment by doamaral** [comment]
Well Done!
